package vistas;

import java.awt.Color;

public class newContact extends javax.swing.JFrame {


    public javax.swing.JTextField getIpTxtField() {
        return ipTxtField;
    }

    public javax.swing.JTextField getNameTxtField() {
        return nameTxtField;
    }

    public javax.swing.JLabel getNewContactButton() {
        return newContactButton;
    }

    /**
     * @return the portTxtField
     */
    public javax.swing.JTextField getPortTxtField() {
        return portTxtField;
    }

    /**
     * Creates new form newContact
     */
    public newContact() {
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                bg.requestFocusInWindow();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ipTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        portTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newContactButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Nuevo contacto");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        nameTxtField.setForeground(new java.awt.Color(204, 204, 204));
        nameTxtField.setText("Ingrese el nombre del contacto...");
        nameTxtField.setBorder(null);
        nameTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTxtFieldMouseClicked(evt);
            }
        });
        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });
        bg.add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 220, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Direccion IP");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        ipTxtField.setForeground(new java.awt.Color(204, 204, 204));
        ipTxtField.setText("Ingrese la direccion IP del contacto...");
        ipTxtField.setBorder(null);
        ipTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipTxtFieldMouseClicked(evt);
            }
        });
        bg.add(ipTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 220, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Puerto");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        portTxtField.setForeground(new java.awt.Color(204, 204, 204));
        portTxtField.setText("Ingrese el puerto del contacto...");
        portTxtField.setBorder(null);
        portTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                portTxtFieldMouseClicked(evt);
            }
        });
        bg.add(portTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, -1));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 220, -1));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, -1));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 102));
        jLabel8.setOpaque(true);
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 170, 340));

        jLabel9.setBackground(new java.awt.Color(0, 0, 102));
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setOpaque(true);
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 90, 340));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, -1));

        newContactButton.setBackground(new java.awt.Color(0, 0, 102));
        newContactButton.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        newContactButton.setForeground(new java.awt.Color(255, 255, 255));
        newContactButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newContactButton.setText("Agregar");
        newContactButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newContactButton.setOpaque(true);
        newContactButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newContactButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newContactButtonMouseExited(evt);
            }
        });
        bg.add(newContactButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void newContactButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newContactButtonMouseEntered
        getNewContactButton().setBackground(new Color(0,102,204));
    }//GEN-LAST:event_newContactButtonMouseEntered

    private void newContactButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newContactButtonMouseExited
        getNewContactButton().setBackground(new Color(0,0,102));
    }//GEN-LAST:event_newContactButtonMouseExited

    private void nameTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTxtFieldMouseClicked
       if (getNameTxtField().getText().equals("Ingrese el nombre del contacto...")){
            getNameTxtField().setText("");
            getNameTxtField().setForeground(Color.BLACK);          
       }
       if (portTxtField.getText().isEmpty()){
           portTxtField.setText("Ingrese el puerto del contacto...");
           portTxtField.setForeground(new Color(204,204,204));
       }
       if (ipTxtField.getText().isEmpty()){
           ipTxtField.setText("Ingrese la direccion IP del contacto...");
           ipTxtField.setForeground(new Color(204,204,204));
       }
    }//GEN-LAST:event_nameTxtFieldMouseClicked

    private void ipTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipTxtFieldMouseClicked
       if (ipTxtField.getText().equals("Ingrese la direccion IP del contacto...")){
            ipTxtField.setText("");
            ipTxtField.setForeground(Color.BLACK);          
       }
       if (portTxtField.getText().isEmpty()){
           portTxtField.setText("Ingrese el puerto del contacto...");
           portTxtField.setForeground(new Color(204,204,204));
       }
       if (getNameTxtField().getText().isEmpty()){
           getNameTxtField().setText("Ingrese el nombre del contacto...");
           getNameTxtField().setForeground(new Color(204,204,204));
       }
    }//GEN-LAST:event_ipTxtFieldMouseClicked

    private void portTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portTxtFieldMouseClicked
       if (portTxtField.getText().equals("Ingrese el puerto del contacto...")){
            portTxtField.setText("");
            portTxtField.setForeground(Color.BLACK);          
       }
       if (getNameTxtField().getText().isEmpty()){
           getNameTxtField().setText("Ingrese el nombre del contacto...");
           getNameTxtField().setForeground(new Color(204,204,204));
       }
       if (ipTxtField.getText().isEmpty()){
           ipTxtField.setText("Ingrese la direccion IP del contacto...");
           ipTxtField.setForeground(new Color(204,204,204));
       }
    }//GEN-LAST:event_portTxtFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTextField ipTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JLabel newContactButton;
    private javax.swing.JTextField portTxtField;
    // End of variables declaration//GEN-END:variables
}
